<a href="https://colab.research.google.com/github/daisuke-shimizu/python-Gakushuin-programming1/blob/main/Programming1_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# サンプルプログラム実行上の注意
プログラミング上達のコツは、

- 短時間に集中してできるだけ大量のプログラムを書くこと
- 試行錯誤を行うこと
- 他人の書いた（動く）プログラムを読むこと
- 更に、自分の目的に合わせてカスタマイズしてみること

を日常的に実行することです。
しかし、限られた授業時間（予習・復習も含む）内で、これらを十分に実行することは至難です。

そこで、
この講義資料は、多数のサンプルプログラムを提供して、
少しでも不足を補うことができるように作成されています。
受講者は、以下の注意を守ってサンプルプログラムをコードセル中で実行することで、
より効率の良い学習を心がけて下さい。

1. サンプルプログラムは、コピペせず、1行1行自分でタイプして書き写して下さい。
コピペでは見逃してしまう、プログラミングの書き方の規則や、プログラミングのコツなど、
自分自身でタイプすることで気づくことができます。
2. サンプルプログラムを書き写す時は、プログラムの意味を考えるよう努めて下さい。
最初は必ずしも最良とは言えないサンプルプログラムを提示して、
後で改良した例を示すなど、この講義資料では、良いプログラムを作成する考え方を効率的に学べるよう、
いろいろな工夫をしています。
3. 意味を理解できない行がある場合には、あまり拘泥せず、先に進んでください。
100%理解しないといけないという思い込みは、プログラミングの上達にとって妨げです。
理解するための努力は必要ですが、Pythonでできることの範囲は非常に広く、
プロのプログラマでも全部は理解していないでしょう。
完璧な理解よりも、**動くプログラムを書くことを最優先の目標**として、
わからない部分は「おまじない」として受け入れることができると、上達も早くなります。
「おまじない」とは、「なぜ効くのかはわからないけれども、使い方は分かっている」という意味です。


# 第12講 Numpyによる数値計算

Numpyは、Pythonにおいて、最も広く使われているライブラリーの一つであり、
数値計算のための強力な機能と高速な計算速度を提供します。
機械学習のためのライブラリであるScikit Learn (sklearn)や、
ニューラルネットをプログラミングするためのライブラリである
TensorFlow、Keras、PyTorchなども、Numpyとの併用を前提にしています。

Numpyを利用する具体的なメリットの一つは、
ベクトルと行列を効率的に取り扱うことができる点にあります。
この資料では、Numpyによる基本的なベクトル・行列の計算や、
ベクトル・行列の要素に対して一度に計算を行う便利な機能を見て行きます。

## ライブラリのインポート

まず、Numpyを使うために、ライブラリをインポートします。
多くの場面でNumpyの関数を利用しますので、npと略称をつけておきます。
以降、この資料では、`numpy`と表記する代わりに、`np`と表記することにします。
```python
import numpy as np
```

In [1]:
import numpy as np

## Ndarrayとベクトル
**Array**とは**配列**を意味する英語で、
Numpyでは、ベクトル・行列・テンソルなどすべてを、arrayとして一元的に扱います。
Numpyで定義されるArrayクラスは、
**Ndarray**（N-Dimensional Array）が正式の名称になりますので、
この資料では、Ndarrayにより、NumpyのArrayクラスを表すこととします。

Ndarrayは、1次元、2次元、3次元、...、と任意の次元の配列を表すことができますが、
数学の用語では、1次元は**ベクトル**、2次元は**行列**、
3次元以上はテンソルという呼び名になります。

まず、1次元のNdarrayから見ていきます。

1次元のNdarrayは、要素の単純な列を表すオブジェクトで、
PythonのListと基本的に同じ概念を表します。

```python
a = [0, 1, 2]
b = np.array([0, 1, 2])
print(a, '\tは、List')
print(b, '\tは、Numpy Array')
```

In [3]:
a = [0, 1, 2]
b = np.array([0, 1, 2])
print(a, '\tは、List')
print(b, '\tは、NdArray')
print(type(a))
print(type(b))

[0, 1, 2] 	は、List
[0 1 2] 	は、NdArray
<class 'list'>
<class 'numpy.ndarray'>


`a`も`b`も、`0`、`1`、`2`の3個の整数を要素とする列という点では同じですが、
`a`はPythonのリスト、`b`はNumpyのArrayです。

表示上では、

- Listでは、要素はコンマ`,`で区切られる
- Numpy Arrayでは、要素はスペースで区切られる

という違いがありますが、要素の列という点では、本質的に同じです。
実際、
```python
print("list(b)はList")
print(list(b))
print("np.array(a)はNdarray")
print(np.array(a))
```
のように、`list()`でNdrrayをListに、
`np.array()`でListをNdarrayにと、相互に変換することができます。

In [5]:
print("list(b)はList")
print(list(b))
print("np.array(a)はNdarray")
print(np.array(a))
print(type(a))
print(type(b))

list(b)はList
[0, 1, 2]
np.array(a)はNdarray
[0 1 2]
<class 'list'>
<class 'numpy.ndarray'>


要素の区切り記号の違いを見れば、
- `b`はNdarrayだが、`list(b)`はList
- `a`はListだが、`np.array(a)`はNdarray

であることが分かります。

この資料では直接関係しませんが、

- Listは異なるタイプの要素を含むことができる
- Ndarrayの同じタイプの要素しか含むことができない

という違いもあります。
```python
a = [1, 'Jan', 2, 'Feb']
b = np.array(a)
print(a)
print(b)
```
を実行してみてください。

In [9]:
a = [1, 'Jan', 2, 'Feb']
b = np.array(a)
print(a)
print(b) #常に同じデータ型の要素しか入らない

[1, 'Jan', 2, 'Feb']
['1' 'Jan' '2' 'Feb']


Listである`a`は、数字と文字列が混在しているのに対し、
Ndarrayである`b`は、全ての要素を文字列に変換して持っています。
Ndarrayの要素は全て同じタイプでなければならず、
数字と文字列の混在を許さないからです。

`a`をListとして、次のコードを実行すると、どのような結果になるか、予想してみて下さい。
```python
a = [0,1,2]
print(a + [3, 4, 5])
print(2 * a)
```

In [11]:
a = [0,1,2]
print(a + [3, 4, 5])
print(2 * a)
print(3 * a)

[0, 1, 2, 3, 4, 5]
[0, 1, 2, 0, 1, 2]
[0, 1, 2, 0, 1, 2, 0, 1, 2]


結果は、予想通りでしたか？

同じプログラムを、Ndarrayである`b`に対して、実行してみます。
```python
b = np.array([0,1,2])
print(b + np.array([3, 4, 5]))
print(2 * b)
```

In [12]:
b = np.array([0,1,2])
print(b + np.array([3, 4, 5]))
print(2 * b)
print(3 * b)

[3 5 7]
[0 2 4]
[0 3 6]


1次元のNdarrayがベクトルを表すという意味がわかったと思います。

`np.array([0,1,2]) + np.array([3,5,6])`は、ベクトルの和

$$
\begin{pmatrix}0\\ 1\\ 2\\\end{pmatrix} + 
\begin{pmatrix}3\\ 4\\ 5\\\end{pmatrix} =
\begin{pmatrix}0 + 3\\ 1 + 4\\ 2 + 5\\\end{pmatrix} =
\begin{pmatrix}3\\ 5\\ 7\\\end{pmatrix} 
$$

であり、
`2 * np.array([0,1,2])`は、ベクトルのスカラー倍

$$
2 \begin{pmatrix}0\\ 1\\ 2\\\end{pmatrix} =
\begin{pmatrix} 2\times 0 \\ 2\times 1\\ 2\times 2\\\end{pmatrix} =
\begin{pmatrix}0\\ 2\\ 4\\\end{pmatrix} 
$$

を表しています。

次に、下のプログラムを試してみましょう。
プログラムを実行する前に、どのような結果になるか、予想してみて下さい。

```python
print(np.array([0,1,2]) * np.array([3,4,5]))
```
      

In [14]:
print(np.array([0,1,2]) * np.array([3,4,5]))
print(np.array([0,1,2]) / np.array([3,4,5]))

[ 0  4 10]
[0.   0.25 0.4 ]


内積（ドット積）を知っている人は、
以下の式で与えられる内積を計算してくれると思ったのではないでしょうか？
$$
\begin{pmatrix}0\\ 1\\ 2\\\end{pmatrix} \cdot
\begin{pmatrix}3\\ 4\\ 5\\\end{pmatrix} =
0 \times 3 + 1 \times 4 + 2 \times 5 = 14
$$

実際には、以下の計算をしています。
$$
\begin{pmatrix}0\\ 1\\ 2\\\end{pmatrix} *
\begin{pmatrix}3\\ 4\\ 5\\\end{pmatrix} =
\begin{pmatrix}0 \times 3\\ 1 \times 4\\ 2 \times 5\\\end{pmatrix} =
\begin{pmatrix}0\\ 4\\ 10\\\end{pmatrix} 
$$

次のプログラムを試して下さい。
```python
print(np.sum(np.array([0,1,2])))
```

**注.** 
`np.sum`は、Numpyで用意されている`sum`関数です。
Pythonでも、`sum`関数を用意していて、
```python
print(sum(np.array([0,1,2])))
```
は、1次元配列の場合は、同じ結果になります。
2次元以上、例えば、行列を引数にした場合には、結果が異なってきます。
この点については後述します。

#### 演習12-1
Ndarrayの乗算`*`と`sum`関数を使って、
Ndarray `x`と`y`の内積を計算する関数`dot(x, y)`のプログラムを作成せよ。

In [19]:
def dot(x, y):
  return np.sum(x * y)
print(dot(np.array([0,1,2]) , np.array([3,4,5])))

14


実は、Numpyにも、内積を計算する関数`dot`が用意されています。
Numpy組み込みの`dot`関数と、
演習12-1で作成した自作の`dot`関数の結果が一致することを確かめて下さい。

```python
print("Numpyのdot\t", np.dot(np.array([0,1,2]), np.array([3,4,5])))
print("自作のdot\t", dot(np.array([0,1,2]), np.array([3,4,5])))
```

In [20]:
print("Numpyのdot\t", np.dot(np.array([0,1,2]), np.array([3,4,5])))
print("自作のdot\t", dot(np.array([0,1,2]), np.array([3,4,5])))

Numpyのdot	 14
自作のdot	 14


## Ndarrayと行列
行列を学んでいない方もいると思いますので、ここでは、「三目並べ」ゲームを使って説明します。

$$
\begin{matrix}
\bigcirc & & \times\\
 & \bigcirc & \bigcirc\\
\times & \times & \times\\
\end{matrix}
$$

ベクトルは1次元の数の並びですが、
行列は2次元の数の並びです。
例えば、上の三目並びの盤面を
次のような行列で表すことができます。

$$
\begin{bmatrix}
1 & 0 & -1\\
0 & 1 & 1\\
-1 & -1 & -1\\
\end{bmatrix}
$$

$\bigcirc$を$1$、$\times$を$-1$、印のついていないマス目を$0$で表しています。

この行列をNdarrayで表すには、
```python
board = np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])
print(board)
```
とします。

実は、`[[1,0,-1], [0,1,1], [-1,-1,-1]]`は、Listを要素に持つListです。
Listは、任意のタイプのオブジェクトを要素に持つことができ、
異なるタイプの要素を含むことも可能です。
したがって、Listを要素に持つListも可能です。
```python
a = [[1,0,-1], [0,1,1], [-1,-1,-1]]
```
とすると、
`a`の要素、`a[0]`、`a[1]`、`a[2]`は、それぞれ、
List`[1,0,-1]`、`[0,1,1]`、`[-1,-1,-1]`になります。
更に、例えば、`a[0]`の要素には、
`a[0][0]`、`a[0][1]`、`a[0][2]`でアクセスすることができます。
次のプログラムを実行して、確かめてみて下さい。

```python
for i in range(3):
    print([a[i][j] for j in range(3)])
```

In [21]:
board = np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])
print(board)

[[ 1  0 -1]
 [ 0  1  1]
 [-1 -1 -1]]


`[[1,0,-1], [0,1,1], [-1,-1,-1]]`はListですが、1次元の場合と同様に、
`np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])`により、
Ndarrayに変換することができます。

#### 演習12-2
以下の盤面を表す行列を、Ndarrayのオブジェクトとして定義せよ。

$$
\begin{matrix}
 \times & \times & \bigcirc\\
 & \times & \\
 & \bigcirc & \bigcirc\\
\end{matrix}
$$



In [24]:
a = [[-1, -1, 1], [0, -1, 0], [0, 1, 1]]
board = np.array([[-1, -1, 1], [0, -1, 0], [0, 1, 1]])
print(board)
print(a[0][0])
print(board[0, 0])

[[-1 -1  1]
 [ 0 -1  0]
 [ 0  1  1]]
-1
-1


List `a`と、Ndarray `board`を以下のように定義します。

```python
a = [[1,0,-1], [0,1,1], [-1,-1,-1]]
board = np.array(a)
```

`a`が表す行列の中心の要素を知るためには、`a[1][1]`としますが、
`board`では、`board[1,1]`とします。
表現としてより単純であるという利点もありますが、
Ndarrayである`board`は、直接的に行列を表現している点が重要です。
- `a[1][1]`は、`a`の1番目の要素`a[1]`の1番目の要素を意味します。
- `board[1,1]`は、行列の1行1列目の成分（要素）を意味します。

要素・行・列の番号は0から振られることに注意して下さい。

#### 演習12-2
以下のプログラムを変更して、
`board`の要素を列挙するプログラムを作成せよ。
```python
for i in range(3):
    print([a[i][j] for j in range(3)])
```


In [14]:
import numpy as np
board = np.array([[-1, -1, 1], [0, -1, 0], [0, 1, 1]])


def repeat(array):
  for i in range(3):
    print([array[i][j] for j in range(3)])

repeat(board)

[-1, -1, 1]
[0, -1, 0]
[0, 1, 1]


行列をNdarrayで表現することの利点の一つとして、部分行列を容易に取り出せることがあります。

List `a = [0, 1, 2, 3, 4]`において、1番目から3番目までの要素を取り出すには、
```python
a = [0, 1, 2, 3, 4]
print(a[1:4])
```
とすれば良いことは、既に学びました。
Listの中の要素の順番は0番から始まり、`1:4`は$(1, 2, 3)$を表すことに注意して下さい。

行列を表現するNdarrayのオブジェクトでは、同じ表現を行と列の両方に適用することができます。
実際、
```python
a = [[1,0,-1], [0,1,1], [-1,-1,-1]]
board = np.array(a)
print(board[0:2, 0:2])
```
とすると、3行3列の行列である`board`から、左上隅の2行2列の部分行列が取り出されます。
確かめてみて下さい。

In [3]:
import numpy as np
a = [[1,0,-1], [0,1,1], [-1,-1,-1]]
board = np.array(a)
print(board)
print(board[0:2, 0:2])

[[ 1  0 -1]
 [ 0  1  1]
 [-1 -1 -1]]
[[1 0]
 [0 1]]


#### 演習12-3
以下の表現が、
Numpy Array`board = np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])`のどの部分行列を表しているか、
それぞれ予想した後、プログラムを実行して確かめよ。
1. `board[1:1, 0:3]`
1. `board[1, 0:3]`
1. `board[1, 0:2]`
1. `board[1, :]`
1. `board[0:3, 2:2]`
1. `board[0:3, 2]`
1. `board[:, 2]`
1. `board[1:2, 0:3]`
1. `board[1:2, :]`
1. `board[:, :]`

In [4]:
board = np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])
print(board)
print(board[1:1, 0:3])
print(board[1, 0:3])
print(board[1, 0:2])
print(board[1, :])
print(board[0:3, 2:2])
print(board[0:3, 2])
print(board[:, 2])
print(board[1:2, 0:3])
print(board[1:2, :])
print(board[:, :])

[[ 1  0 -1]
 [ 0  1  1]
 [-1 -1 -1]]
[]
[0 1 1]
[0 1]
[0 1 1]
[]
[-1  1 -1]
[-1  1 -1]
[[0 1 1]]
[[0 1 1]]
[[ 1  0 -1]
 [ 0  1  1]
 [-1 -1 -1]]


ところで、Pythonの関数`sum`とNumpyの関数`np.sum`とは、が違うという述べましたが、次のプログラムを実行してみて下さい。
```python
print(sum(board))
print(np.sum(board))
```

In [5]:
print(sum(board))
print(np.sum(board))

[ 0  0 -1]
-1


- `sum(board)`では、
```python
np.array([1,0,-1])+np.array([0,1,1])+np.array([-1,-1,-1])
```
を計算します。
これは、Pythonの`sum`関数は、`board`をListと考え、Listの要素の和を計算するからです。
`board`の要素は、Ndarrayですので、その和はベクトルとしての和（成分ごとの和）になります。
- `np.sum(board)`では、`board`を行列であると考え、$3\times 3 = 9$個の成分の和を計算します。

#### 演習12-4
演習12-3の各表現に対して、`sum()`と`np.sum()`を適用し、その値を求めよ。
コードセルで計算する前に、どのような値が返ってくるか予測せよ。

In [8]:
print(board)
print(sum(board[1:1, 0:3]))
print(sum(board[1, 0:3]))
print(sum(board[1, 0:2]))
print(sum(board[1, :]))
print(sum(board[0:3, 2:2]))
print(sum(board[0:3, 2]))
print(sum(board[:, 2]))
print(sum(board[1:2, 0:3]))
print(sum(board[1:2, :]))
print(sum(board[:, :]))

print(np.sum(board[1:1, 0:3]))
print(np.sum(board[1, 0:3]))
print(np.sum(board[1, 0:2]))
print(np.sum(board[1, :]))
print(np.sum(board[0:3, 2:2]))
print(np.sum(board[0:3, 2]))
print(np.sum(board[:, 2]))
print(np.sum(board[1:2, 0:3]))
print(np.sum(board[1:2, :]))
print(np.sum(board[:, :]))

[[ 1  0 -1]
 [ 0  1  1]
 [-1 -1 -1]]
0
2
1
2
[]
-1
-1
[0 1 1]
[0 1 1]
[ 0  0 -1]
0
2
1
2
0
-1
-1
2
2
-1


## 盤面の勝敗判定
Ndarrayで表現された三目並べの盤面の勝敗を判定する関数`judge()`を作成します。
盤面を表現するNumpy Array`board`に対して、
`judge(board)`の返り値を次のように定めます。
- 先手（ここでは$\times$とする）が勝っていれば、$1$を返す。
- 後手（ここでは$\bigcirc$とする）が勝っていれば、$-1$を返す。
- どちらの勝ちでもなければ、$0$を返す。

例えば、
$$
\begin{matrix}
\bigcirc & & \times\\
 & \bigcirc & \bigcirc\\
\times & \times & \times\\
\end{matrix}
$$
は、次の行列で表されます。
$$
\begin{bmatrix}
1 & 0 & -1\\
0 & 1 & 1\\
-1 & -1 & -1\\
\end{bmatrix}
$$
この盤面は、最下行が$\times$で埋まっているので、先手（$\times$）の勝ちです。
従って、
`board = np.array([[1,0,-1], [0,1,1], [-1,-1,-1]])`に対して、
`judge(board)`の値は$-1$にならなくてはなりません。

一方、「最下行が$\times$で埋まっている」という事実をプログラムで確認するためには、
`board`の第2行が`[-1, -1, -1]`であることを確かめれば良いのですが、
これは`np.sum(board[2, :])`の値が$-3$であることを確認することと同じです。
従って、`board`の第2行における勝負を判定するには、次のプログラムを実行すれば良いことになります。
```python
p = np.sum(board[2, :])
if p == 3:
    return 1 # 後手勝ち
elif p == -3:
    return -1 # 先手勝ち
```
第0行、第1行、第2行のいずれかが、$\times$か$\bigcirc$で埋められているケースでは、
次のプログラムで、勝者を判定できることになります。

```python
for r in range(3):
    p = np.sum(board[r, :])
    if p == 3:
        return 1 # 後手勝ち
    elif p == -3:
        return -1 # 先手勝ち
```

これを、関数`judge`の中に埋め込んでみましょう。
```python
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    return 0
```
この関数は、先手か後手が、いずれかの行を埋めて勝負を決める場合には、正しく判定を行うことができます。

例えば、盤面が

$$
\begin{matrix}
\bigcirc & & \times\\
 & \bigcirc & \bigcirc\\
\times & \times & \times\\
\end{matrix}
$$

で、`board`がこの盤面を表現するNdarrayである場合は、
以下のように、`judge(board)`は正しい勝敗の判定を返します。
`board`を引数に指定しましたので、`b`は`board`を意味します。

1. `r = 0`では、`b[0, :]`は`[1 0 -1]`なので、`p = np.sum(b[0, :]`の値は$0$。
`p`の値は、$3$でも、$-3$でもないので、`for`ループの次の繰り返しに進みます。
1. `r = 1`では、`b[1, :]`は`[0 1 1]`なので、`p = np.sum(b[1, :]`の値は$2$。
`p`の値は、$3$でも、$-3$でもないので、`for`ループの次の繰り返しに進みます。
1. `r = 2`では、`b[2, :]`は`[-1 -1 -1]`なので、`p = np.sum(b[1, :]`の値は$-3$。
従って、`if p == -3:`が成立し、`return -1`により、$-1$を返す。

#### 演習12-5
上記の`judge`関数を下のコードセルで定義し、
以下の盤面に対して、正しく判定できているかを調べよ。
1. 　
$$
\begin{matrix}
\bigcirc & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
 & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \times & \bigcirc\\
 & \times & \bigcirc\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
\bigcirc & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \bigcirc & \times\\
\bigcirc & \times & \\
\end{matrix}
$$

In [27]:
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    return 0
b1 = np.array([[1, 1, 1], [0, -1, 1], [0, -1, -1]])
print(judge(b1))
b2 = np.array([[-1, 1, 1], [-1, -1, 1], [0, -1, 1]])
print(judge(b2))
b3 = np.array([[-1, 1, 1], [0, -1, 1], [1, -1, -1]])
print(judge(b3))
b4 = np.array([[-1, 1, 1], [-1, 1, -1], [1, -1, 0]])
print(judge(b4))

1
0
0
0


次に、列方向（縦方向）に$\bigcirc$か$\times$が並んだ場合の勝敗の判定法を考えてみましょう。
実は、前述のプログラムにおいて、行を列に入れ替えるだけですので、難しくありません。
$r$行の成分の和を計算するプログラム行
```python
p = np.sum(b[r, :])
```
を、行と列を入れ替えた
```python
p = np.sum(b[:, r])
```
に変更すれば、$r$列の成分の和を計算することができます。

#### 演習12-6
横方向の並びで勝敗を判定する前述の`judge`関数に、
列方向の$\bigcirc\times$の並びを検査して勝敗を判定するプログラムを追加することで、
`judge`関数の定義を更新せよ。
更に、この関数が、以下の盤面に対して、正しく判定できているかを調べよ。
1. 　
$$
\begin{matrix}
\bigcirc & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
 & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \times & \bigcirc\\
 & \times & \bigcirc\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
\bigcirc & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \bigcirc & \times\\
\bigcirc & \times & \\
\end{matrix}
$$

In [34]:
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    for r in range(3):
        p = np.sum(b[:, r])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    return 0
print(judge(b1))
print(judge(b2))
print(judge(b3))
print(judge(b4))

1
1
0
0


左上隅から右下隅までの対角線上のマス目が、$\bigcirc$か$\times$のいずれかで埋められた時も、
勝敗が決まります。
行列では、この対角線上の成分を、**対角成分**と呼びます。
数学では行列の対角成分は重要な意味を持つため、
Numpyでは、Ndarrayから対角成分を取り出すための関数`np.diag()`が用意されています。

以下のプログラムを実行して、`np.diag`関数の機能を確認して下さい。

```python
b = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(b)
print("の対角成分は", np.diag(b))
```

In [31]:
b = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(b)
print("の対角成分は", np.diag(b))

berror = np.array([[0,1,2], [3,4,5], [6,7,8,9]])
print(berror)
print("の対角成分は", np.diag(berror))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
の対角成分は [0 4 8]
[list([0, 1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]
の対角成分は [[list([0, 1, 2]) 0 0]
 [0 list([3, 4, 5]) 0]
 [0 0 list([6, 7, 8, 9])]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """


`np.diag`関数を使えば、以下のプログラムで、右下がりの対角線が、
$\bigcirc$もしくは$\times$で埋められている時の勝者を判定することができます。

```python
p = np.sum(np.diag(b))
if p == 3:
    return 1
if p == -3
    return -1
```

#### 演習12-7
縦横の方向で勝敗を判定する前述の`judge`関数に、
右下がりの対角線方向の$\bigcirc\times$の並びを検査して勝敗を判定するプログラムを追加することで、
`judge`関数の定義を更新せよ。
更に、この関数が、以下の盤面に対して、正しく判定できているかを調べよ。
1. 　
$$
\begin{matrix}
\bigcirc & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
 & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \times & \bigcirc\\
 & \times & \bigcirc\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
\bigcirc & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \bigcirc & \times\\
\bigcirc & \times & \\
\end{matrix}
$$

In [36]:
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    for r in range(3):
        p = np.sum(b[:, r])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    p = np.sum(np.diag(b))
    if p == 3:
        return 1
    if p == -3:
        return -1
    return 0
print(judge(b1))
print(judge(b2))
print(judge(b3))
print(judge(b4))

1
1
-1
0


2次元のNumpy Arrayの右下がりの成分を取り出すためには、
`np.diag()`という関数が用意されていますが、残念ながら、
左下りの対角成分を直接取り出すための関数は用意されていません。
ただ、
`np.fliplr()`という関数を一回挟んで、
`np.diag(np.fliplr(b))`とすれば、
左下りの対角線上の成分（要素）を取り出すことが可能になります。

#### 演習12-8
関数`np.fliplr`が、どのような作用を持つのか、
自分でテストプログラムを書いて確かめよ。

In [41]:
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    for r in range(3):
        p = np.sum(b[:, r])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    p = np.sum(np.diag(b))
    if p == 3:
        return 1
    if p == -3:
        return -1
    p = np.sum(np.diag(np.fliplr(b))) # fliplrのlとrはleftとright
    if p == 3:
        return 1
    if p == -3:
        return -1
    return 0
print(b)
print(np.fliplr(b))
print(judge(b1))
print(judge(b2))
print(judge(b3))
print(judge(b4))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
1
1
-1
1


#### 演習12-9
縦横方向と右下がりの対角線方向で勝敗を判定する前述の`judge`関数に、
左下がりの対角線方向の$\bigcirc\times$の並びを検査して勝敗を判定するプログラムを追加することで、
`judge`関数の定義を完成させよ。
更に、この関数が、以下の盤面に対して、正しく判定できているかを調べよ。
1. 　
$$
\begin{matrix}
\bigcirc & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
 & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \times & \bigcirc\\
 & \times & \bigcirc\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
 & \times & \bigcirc\\
\bigcirc & \times & \times\\
\end{matrix}
$$
1. 　
$$
\begin{matrix}
\times & \bigcirc & \bigcirc\\
\times & \bigcirc & \times\\
\bigcirc & \times & \\
\end{matrix}
$$

In [42]:
def judge(b):
    for r in range(3):
        p = np.sum(b[r, :])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    for r in range(3):
        p = np.sum(b[:, r])
        if p == 3:
            return 1 # 後手勝ち
        if p == -3:
            return -1 # 先手勝ち
    p = np.sum(np.diag(b))
    if p == 3:
        return 1
    if p == -3:
        return -1
    p = np.sum(np.diag(np.fliplr(b))) # fliplrのlとrはleftとright
    if p == 3:
        return 1
    if p == -3:
        return -1
    return 0

print(judge(b1))
print(judge(b2))
print(judge(b3))
print(judge(b4))

1
1
-1
1


## Ndarrayの要素に対する一括計算
Ndarrayでは、成分ごとの計算を一括して実行できる、便利な機能があります。

例えば、
```python
A = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(A**2)
```
を実行してみて下さい。

In [43]:
A = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(A**2)

[[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]


Pythonでは、例えば、`2**2`は$2^2$を表しますが、
Ndarray`A`に対して、`A**2`とすると、
各成分を二乗した`A`と同じ行数・列数のNdarrayを表します。

$$
\begin{bmatrix}
0 & 1 & 2\\ 3 & 4 & 5\\ 6 & 7 & 8\\ 
\end{bmatrix} 
\mathrm{**} 2 = 
\begin{bmatrix}
0^2 & 1^2 & 2^2\\ 
3^2 & 4^2 & 5^2\\ 
6^2 & 7^2 & 8^2\\ 
\end{bmatrix} = 
\begin{bmatrix}
0 & 1 & 4\\ 
9 & 16 & 25\\ 
36 & 49 & 64\\ 
\end{bmatrix}
$$

#### 演習12-10
`A = np.array([[0,1,2], [3,4,5], [6,7,8]])`に対して、
以下の計算を実行せよ。
1. `A+1`
1. `A-1`
1. `A*2`
1. `A/2`
1. `A**(1/2)`
1. `2**A`



In [10]:
A = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(A+1)
print(A-1)
print(A*2)
print(A/1)
print(A**(1/2))
print(2**A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


また、Numpyで用意されている多くの数学の関数も、
Ndarrayを引数にとって、成分に一括して関数を適用することができます。
例えば、Mathライブラリーに用意されている関数`math.sqrt`は、
数値に対して、平方根を計算します。
```python
import math
a = 2
print(math.sqrt(a))
a = 3
print(math.sqrt(a))
```

In [11]:
import math
a = 2
print(math.sqrt(a))
a = 3
print(math.sqrt(a))

1.4142135623730951
1.7320508075688772


`math.sqrt`が引数に取れるのは、数値に限り、
Ndarray`A = np.array([[0,1,2], [3,4,5], [6,7,8]])`を、
引数に取ることはできません。
```python
print(math.sqrt(A))
```
を実行しようとすると、エラーが出る筈です。

ここで、Numpyで用意されている`sqrt`関数を利用すると、
Ndarrayの各要素の平方根を一括して計算することができます。
次のプログラムを実行してみて下さい。

```python
print(np.sqrt(A))
```

In [14]:
# print(math.sqrt(A))
print(np.sqrt(A))

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


Numpyで用意されている数学の関数の多くは、
Ndarrayを引数に取ることが可能で、
成分ごとに関数の値を計算してくれます。

#### 演習 12-11
`A = np.array([[0,1,2], [3,4,5], [6,7,8]])`に対して、
以下の計算を実行せよ。
1. `np.exp(A)`
1. `np.log(1+A)`　（$\log 0 = -\infty$なので、1を足す）
1. `np.cos(A)`
1. `np.sin(A)`
1. `np.tan(A)`

In [15]:
A = np.array([[0,1,2], [3,4,5], [6,7,8]])

print(np.exp(A))
print(np.log(1+A))
print(np.cos(A))
print(np.sin(A))
print(np.tan(A))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00]
 [2.00855369e+01 5.45981500e+01 1.48413159e+02]
 [4.03428793e+02 1.09663316e+03 2.98095799e+03]]
[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]
[[ 1.          0.54030231 -0.41614684]
 [-0.9899925  -0.65364362  0.28366219]
 [ 0.96017029  0.75390225 -0.14550003]]
[[ 0.          0.84147098  0.90929743]
 [ 0.14112001 -0.7568025  -0.95892427]
 [-0.2794155   0.6569866   0.98935825]]
[[ 0.          1.55740772 -2.18503986]
 [-0.14254654  1.15782128 -3.38051501]
 [-0.29100619  0.87144798 -6.79971146]]
